# Generated by Django 2.2.10 on 2020-02-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR')])),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'OTP'), (5, 'Pumb'), (6, 'Alfa')])),
                ('buy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
