# Generated by Django 2.2.10 on 2020-04-09 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20200330_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
